title: Prepare to run a Code Club - Week 1
hero_image: images/banner.png
description: default-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Welcome to the course
  - title: Meet the team
  - title: Get Prepared
  - title: About Code Club
  - title: What do I need to know to be a Code Club volunteer?
  - title: How to register with Code Club
    completion:
      - engaged
  - title: Let’s get planning!
  - title: The young people at your club
  - title: Safeguarding
    completion:
      - internal
  - title: Get your hardware ready
  - title: Get your software ready
  - title: An introduction to Scratch
    completion:
      - external

  - title: Week 1 recap

